Move brakeman config to file and ignore errors
A parsing error is occuring resulting
from brakeman not being upto date with
ruby 2.7 triple dot `...` argument passing.

Specifically
```
Error: app/helpers/hearing_helper.rb:4 :: parse error on value "..." (tDOT3) Could not parse app/helpers/hearing_helper.rb
```

We are only interested in security warnings
from brakeman so `:exit_on_error: false`
prevents non-zero return codes for parsing
errors.

In addition, since we are now passing three
args/switches to brakeman I have put these
in the default brakeman config file location
so circle will also pick them up.

Haved bumped an existing issue with brakeman
for now.

https://github.com/presidentbeef/brakeman/issues/1483