Add dependency to controller
Not having this is causing on pod start up

```
Unable to load application: NameError: uninitialized constant CourtDataAdaptor::Errors
Did you mean?  Errno
bundler: failed to load command: puma (/usr/local/bundle/bin/puma)
NameError: uninitialized constant CourtDataAdaptor::Errors
Did you mean?  Errno
```