exclude rubocop from run
Because rubocop appears to be complaining
about rubocop.yaml files of gems

example:
```
vendor/bundle/ruby/2.7.0/gems/nio4r-2.5.2/.rubocop.yml: Metrics/LineLength has the wrong namespace - should be Layout
Error: The `Lint/HandleExceptions` cop has been renamed to `Lint/SuppressedException`.
(obsolete configuration found in vendor/bundle/ruby/2.7.0/gems/nio4r-2.5.2/.rubocop.yml, please update it)
Finished in 0.8796651389984618 seconds

Exited with code exit status 2
```